// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/AkankshaNichrelay/Auth-Backend/internal/auth"
	"github.com/AkankshaNichrelay/Auth-Backend/internal/config"
	"github.com/AkankshaNichrelay/Auth-Backend/internal/db"
	"github.com/AkankshaNichrelay/Auth-Backend/internal/handler"
	"log"
)

// Injectors from wire.go:

func InitializeAndRun(ctx context.Context, logger *log.Logger, configFile string) (*handler.Handler, error) {
	configConfig, err := config.New(configFile)
	if err != nil {
		return nil, err
	}
	dbConfig := config.NewDBConfig(configConfig)
	mysql, err := db.New(logger, dbConfig)
	if err != nil {
		return nil, err
	}
	authAuth := auth.New(mysql)
	handlerHandler := handler.New(logger, authAuth)
	return handlerHandler, nil
}
